export * from './anagrafica-candidato.service';
export * from './anagrafica-candidato-update.component';
export * from './anagrafica-candidato-own-update.component';
export * from './anagrafica-candidato-delete-dialog.component';
export * from './anagrafica-candidato-detail.component';
export * from './anagrafica-candidato-own-detail.component';
export * from './anagrafica-candidato.component';
export * from './anagrafica-candidato.route';
export * from './anagrafica-candidato-own.route';
