version: '2'
services:
  jemoloapplication-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/jemoloApplication/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jemoloappownr
      - POSTGRES_PASSWORD=jemoloappownr
    ports:
      - 5432:5432
