export * from './candidato.service';
export * from './candidato-update.component';
export * from './candidato-own-update.component';
export * from './candidato-delete-dialog.component';
export * from './candidato-detail.component';
export * from './candidato-own-detail.component';
export * from './candidato.component';
export * from './candidato.route';
export * from './candidato-own.route';
